Added step Clean server space in ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -174,6 +174,10 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_KEY }}
 
+      - name: Clean server space
+        run: |
+          ssh user@server "docker system prune -f && sudo apt clean"
+
       - name: Run Docker
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'  
@@ -211,6 +215,7 @@ jobs:
             sudo systemctl daemon-reload
             sudo systemctl enable atomic_habits.service
           EOF
+
       - name: Restart application
         run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
@@ -218,3 +223,11 @@ jobs:
             docker compose -f ~/atomic_habits/docker-compose.yml down || true
             sudo systemctl start atomic_habits.service          
           EOF
+
+#      - name: Verify deployment`
+#        run: |
+#          if ! curl -sSf http://158.160.192.46 >/dev/null; then
+#            echo "::error::App is not running! Checking logs..."
+#            ssh user@158.160.192.46 "sudo docker ps -a && sudo docker logs myapp"
+#            exit 1
+#          fi
